# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Class for exceptions when there is a network error, status code error, etc.
  class APIException < CoreLibrary::ApiException
  end
end
