# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Indicates if rewards were earned or redeemed.
  class Action9Enum
    ACTION9_ENUM = [
      # TODO: Write general description for EARNED
      EARNED = 'Earned'.freeze,

      # TODO: Write general description for REDEEMED
      REDEEMED = 'Redeemed'.freeze,

      # TODO: Write general description for RETURNED
      RETURNED = 'Returned'.freeze,

      # TODO: Write general description for REMOVED
      REMOVED = 'Removed'.freeze,

      # TODO: Write general description for LATECANCELED
      LATECANCELED = 'LateCanceled'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACTION9_ENUM.include?(value)
    end
  end
end
