# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # ApiError1 Model.
  class ApiError1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The text of the message. Each message is specific to the error that caused
    # it.
    # For example, if the the error type is `InvalidFileFormat`, 
    # the message could say "The photo you attempted to upload is not a
    # supported file type."
    # @return [String]
    attr_accessor :message

    # The type of error that occurred, for example, `ClientNotFound` or
    # `InvalidClassId`.
    # @return [String]
    attr_accessor :code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['message'] = 'Message'
      @_hash['code'] = 'Code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        message
        code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(message = SKIP, code = SKIP)
      @message = message unless message == SKIP
      @code = code unless code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      message = hash.key?('Message') ? hash['Message'] : SKIP
      code = hash.key?('Code') ? hash['Code'] : SKIP

      # Create object from extracted values.
      ApiError1.new(message,
                    code)
    end
  end
end
