# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # A color used by products.
  class Color < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique ID of the product color.
    # @return [Integer]
    attr_accessor :id

    # The name of the color of product.
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'Id'
      @_hash['name'] = 'Name'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        name
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = SKIP, name = SKIP)
      @id = id unless id == SKIP
      @name = name unless name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('Id') ? hash['Id'] : SKIP
      name = hash.key?('Name') ? hash['Name'] : SKIP

      # Create object from extracted values.
      Color.new(id,
                name)
    end
  end
end
