# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module MindbodyPublicApi
  # A contact log comment.
  class ContactLogComment < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The comment’s ID.
    # @return [Integer]
    attr_accessor :id

    # The comment’s body text.
    # @return [String]
    attr_accessor :text

    # The local time when the comment was created.
    # @return [DateTime]
    attr_accessor :created_date_time

    # The Staff
    # @return [Staff]
    attr_accessor :created_by

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'Id'
      @_hash['text'] = 'Text'
      @_hash['created_date_time'] = 'CreatedDateTime'
      @_hash['created_by'] = 'CreatedBy'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        text
        created_date_time
        created_by
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = SKIP, text = SKIP, created_date_time = SKIP,
                   created_by = SKIP)
      @id = id unless id == SKIP
      @text = text unless text == SKIP
      @created_date_time = created_date_time unless created_date_time == SKIP
      @created_by = created_by unless created_by == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('Id') ? hash['Id'] : SKIP
      text = hash.key?('Text') ? hash['Text'] : SKIP
      created_date_time = if hash.key?('CreatedDateTime')
                            (DateTimeHelper.from_rfc3339(hash['CreatedDateTime']) if hash['CreatedDateTime'])
                          else
                            SKIP
                          end
      created_by = Staff.from_hash(hash['CreatedBy']) if hash['CreatedBy']

      # Create object from extracted values.
      ContactLogComment.new(id,
                            text,
                            created_date_time,
                            created_by)
    end

    def to_custom_created_date_time
      DateTimeHelper.to_rfc3339(created_date_time)
    end
  end
end
