# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # crosssite/copycreditcard
  class CopyCreditCardRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The siteId of the source clientId.
    # @return [Integer]
    attr_accessor :source_site_id

    # The clientId at the source siteId.
    # @return [String]
    attr_accessor :source_client_id

    # The siteId of the target clientId.
    # @return [Integer]
    attr_accessor :target_site_id

    # The clientId at the target siteId.
    # @return [String]
    attr_accessor :target_client_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_site_id'] = 'SourceSiteId'
      @_hash['source_client_id'] = 'SourceClientId'
      @_hash['target_site_id'] = 'TargetSiteId'
      @_hash['target_client_id'] = 'TargetClientId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        source_site_id
        source_client_id
        target_site_id
        target_client_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(source_site_id = SKIP, source_client_id = SKIP,
                   target_site_id = SKIP, target_client_id = SKIP)
      @source_site_id = source_site_id unless source_site_id == SKIP
      @source_client_id = source_client_id unless source_client_id == SKIP
      @target_site_id = target_site_id unless target_site_id == SKIP
      @target_client_id = target_client_id unless target_client_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_site_id = hash.key?('SourceSiteId') ? hash['SourceSiteId'] : SKIP
      source_client_id =
        hash.key?('SourceClientId') ? hash['SourceClientId'] : SKIP
      target_site_id = hash.key?('TargetSiteId') ? hash['TargetSiteId'] : SKIP
      target_client_id =
        hash.key?('TargetClientId') ? hash['TargetClientId'] : SKIP

      # Create object from extracted values.
      CopyCreditCardRequest.new(source_site_id,
                                source_client_id,
                                target_site_id,
                                target_client_id)
    end
  end
end
