# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # DeactivatePromoCodeRequest Model.
  class DeactivatePromoCodeRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The promocodeID
    # @return [Integer]
    attr_accessor :promotion_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['promotion_id'] = 'PromotionId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(promotion_id = nil)
      @promotion_id = promotion_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      promotion_id = hash.key?('PromotionId') ? hash['PromotionId'] : nil

      # Create object from extracted values.
      DeactivatePromoCodeRequest.new(promotion_id)
    end
  end
end
