# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # The prefered gender of the appointment provider.  Possible values are: *
  # None * Female * Male
  class GenderPreferenceEnum
    GENDER_PREFERENCE_ENUM = [
      # TODO: Write general description for NONE
      NONE = 'None'.freeze,

      # TODO: Write general description for FEMALE
      FEMALE = 'Female'.freeze,

      # TODO: Write general description for MALE
      MALE = 'Male'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      GENDER_PREFERENCE_ENUM.include?(value)
    end
  end
end
