# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetClientIndexesResponse Model.
  class GetClientIndexesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the client indexes.
    # @return [Array[ClientIndex]]
    attr_accessor :client_indexes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client_indexes'] = 'ClientIndexes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        client_indexes
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(client_indexes = SKIP)
      @client_indexes = client_indexes unless client_indexes == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      client_indexes = nil
      unless hash['ClientIndexes'].nil?
        client_indexes = []
        hash['ClientIndexes'].each do |structure|
          client_indexes << (ClientIndex.from_hash(structure) if structure)
        end
      end

      client_indexes = SKIP unless hash.key?('ClientIndexes')

      # Create object from extracted values.
      GetClientIndexesResponse.new(client_indexes)
    end
  end
end
