# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetClassDescriptionsResponse Model.
  class GetClassDescriptionsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # Contains information about the class descriptions.
    # @return [Array[ClassDescription]]
    attr_accessor :class_descriptions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['class_descriptions'] = 'ClassDescriptions'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        class_descriptions
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, class_descriptions = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @class_descriptions = class_descriptions unless class_descriptions == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      class_descriptions = nil
      unless hash['ClassDescriptions'].nil?
        class_descriptions = []
        hash['ClassDescriptions'].each do |structure|
          class_descriptions << (ClassDescription.from_hash(structure) if structure)
        end
      end

      class_descriptions = SKIP unless hash.key?('ClassDescriptions')

      # Create object from extracted values.
      GetClassDescriptionsResponse.new(pagination_response,
                                       class_descriptions)
    end
  end
end
