# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetClientPurchasesResponse Model.
  class GetClientPurchasesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # Contains information that describes the item sold and the payment.
    # @return [Array[ClientPurchaseRecord]]
    attr_accessor :purchases

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['purchases'] = 'Purchases'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        purchases
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, purchases = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @purchases = purchases unless purchases == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      purchases = nil
      unless hash['Purchases'].nil?
        purchases = []
        hash['Purchases'].each do |structure|
          purchases << (ClientPurchaseRecord.from_hash(structure) if structure)
        end
      end

      purchases = SKIP unless hash.key?('Purchases')

      # Create object from extracted values.
      GetClientPurchasesResponse.new(pagination_response,
                                     purchases)
    end
  end
end
