# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Get Relationships Response Model
  class GetRelationshipsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # A list of relationships.
    # @return [Array[Relationship]]
    attr_accessor :relationships

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['relationships'] = 'Relationships'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        relationships
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, relationships = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @relationships = relationships unless relationships == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      relationships = nil
      unless hash['Relationships'].nil?
        relationships = []
        hash['Relationships'].each do |structure|
          relationships << (Relationship.from_hash(structure) if structure)
        end
      end

      relationships = SKIP unless hash.key?('Relationships')

      # Create object from extracted values.
      GetRelationshipsResponse.new(pagination_response,
                                   relationships)
    end
  end
end
