# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetSessionTypesResponse Model.
  class GetSessionTypesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # Contains information about sessions.
    # @return [Array[SessionType]]
    attr_accessor :session_types

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['session_types'] = 'SessionTypes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        session_types
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, session_types = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @session_types = session_types unless session_types == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      session_types = nil
      unless hash['SessionTypes'].nil?
        session_types = []
        hash['SessionTypes'].each do |structure|
          session_types << (SessionType.from_hash(structure) if structure)
        end
      end

      session_types = SKIP unless hash.key?('SessionTypes')

      # Create object from extracted values.
      GetSessionTypesResponse.new(pagination_response,
                                  session_types)
    end
  end
end
