# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetCustomClientFieldsResponse Model.
  class GetCustomClientFieldsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # Contains information about the available custom client fields.
    # @return [Array[CustomClientField]]
    attr_accessor :custom_client_fields

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['custom_client_fields'] = 'CustomClientFields'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        custom_client_fields
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, custom_client_fields = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @custom_client_fields = custom_client_fields unless custom_client_fields == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      custom_client_fields = nil
      unless hash['CustomClientFields'].nil?
        custom_client_fields = []
        hash['CustomClientFields'].each do |structure|
          custom_client_fields << (CustomClientField.from_hash(structure) if structure)
        end
      end

      custom_client_fields = SKIP unless hash.key?('CustomClientFields')

      # Create object from extracted values.
      GetCustomClientFieldsResponse.new(pagination_response,
                                        custom_client_fields)
    end
  end
end
