# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetClientAccountBalancesResponse Model.
  class GetClientAccountBalancesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # A list of clients.
    # @return [Array[Client]]
    attr_accessor :clients

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['clients'] = 'Clients'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        clients
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, clients = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @clients = clients unless clients == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      clients = nil
      unless hash['Clients'].nil?
        clients = []
        hash['Clients'].each do |structure|
          clients << (Client.from_hash(structure) if structure)
        end
      end

      clients = SKIP unless hash.key?('Clients')

      # Create object from extracted values.
      GetClientAccountBalancesResponse.new(pagination_response,
                                           clients)
    end
  end
end
