# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetClientDuplicatesResponse Model.
  class GetClientDuplicatesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # The requested clients.
    # @return [Array[ClientDuplicate]]
    attr_accessor :client_duplicates

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['client_duplicates'] = 'ClientDuplicates'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        client_duplicates
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, client_duplicates = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @client_duplicates = client_duplicates unless client_duplicates == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      client_duplicates = nil
      unless hash['ClientDuplicates'].nil?
        client_duplicates = []
        hash['ClientDuplicates'].each do |structure|
          client_duplicates << (ClientDuplicate.from_hash(structure) if structure)
        end
      end

      client_duplicates = SKIP unless hash.key?('ClientDuplicates')

      # Create object from extracted values.
      GetClientDuplicatesResponse.new(pagination_response,
                                      client_duplicates)
    end
  end
end
