# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetActiveSessionTimesResponse Model.
  class GetActiveSessionTimesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # List of available start times for active sessions. Note the following:
    # * The times returned represent possibilities for scheduling a session, not
    # necessarily currently scheduled sessions.
    # * The response includes either all schedule types or those filtered by
    # supplying `ScheduleType` or `SessionTypeIds`.
    # * Each session has an associated schedule type, but when you supply
    # `SessionTypeIds`, they may map to one or more of the schedule types.
    # @return [Array[String]]
    attr_accessor :active_session_times

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['active_session_times'] = 'ActiveSessionTimes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        active_session_times
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, active_session_times = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @active_session_times = active_session_times unless active_session_times == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      active_session_times =
        hash.key?('ActiveSessionTimes') ? hash['ActiveSessionTimes'] : SKIP

      # Create object from extracted values.
      GetActiveSessionTimesResponse.new(pagination_response,
                                        active_session_times)
    end
  end
end
