# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Enables to retrieve cross regional formula notes for a client, or for a
  # specific appointment. The two parameters are optional, however at least one
  # must be provided. This endpoint supports pagination.
  class GetClientFormulaNotesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # Contains details about the client’s formula.
    # @return [Array[FormulaNoteResponse]]
    attr_accessor :formula_notes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['formula_notes'] = 'FormulaNotes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        formula_notes
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, formula_notes = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @formula_notes = formula_notes unless formula_notes == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      formula_notes = nil
      unless hash['FormulaNotes'].nil?
        formula_notes = []
        hash['FormulaNotes'].each do |structure|
          formula_notes << (FormulaNoteResponse.from_hash(structure) if structure)
        end
      end

      formula_notes = SKIP unless hash.key?('FormulaNotes')

      # Create object from extracted values.
      GetClientFormulaNotesResponse.new(pagination_response,
                                        formula_notes)
    end
  end
end
