# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Contains information about the get PickASpot class response.
  class GetPickASpotClassResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the PickASpot classes.
    # @return [Array[PickASpotClass]]
    attr_accessor :classes

    # Contains information about the pagination used.
    # @return [Pagination]
    attr_accessor :pagination

    # Contains information about the response message detail.
    # @return [ResponseDetails]
    attr_accessor :response_details

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['classes'] = 'classes'
      @_hash['pagination'] = 'pagination'
      @_hash['response_details'] = 'responseDetails'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        classes
        pagination
        response_details
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(classes = SKIP, pagination = SKIP, response_details = SKIP)
      @classes = classes unless classes == SKIP
      @pagination = pagination unless pagination == SKIP
      @response_details = response_details unless response_details == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      classes = nil
      unless hash['classes'].nil?
        classes = []
        hash['classes'].each do |structure|
          classes << (PickASpotClass.from_hash(structure) if structure)
        end
      end

      classes = SKIP unless hash.key?('classes')
      pagination = Pagination.from_hash(hash['pagination']) if hash['pagination']
      response_details = ResponseDetails.from_hash(hash['responseDetails']) if
        hash['responseDetails']

      # Create object from extracted values.
      GetPickASpotClassResponse.new(classes,
                                    pagination,
                                    response_details)
    end
  end
end
