# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Get transactions response properties
  class GetTransactionsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the pagination to use.
    # @return [PaginationResponse]
    attr_accessor :pagination_response

    # Contains the transaction objects, each of which describes the transaction
    # details for a purchase event.
    # @return [Array[Transaction]]
    attr_accessor :transactions

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pagination_response'] = 'PaginationResponse'
      @_hash['transactions'] = 'Transactions'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pagination_response
        transactions
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pagination_response = SKIP, transactions = SKIP)
      @pagination_response = pagination_response unless pagination_response == SKIP
      @transactions = transactions unless transactions == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pagination_response = PaginationResponse.from_hash(hash['PaginationResponse']) if
        hash['PaginationResponse']
      # Parameter is an array, so we need to iterate through it
      transactions = nil
      unless hash['Transactions'].nil?
        transactions = []
        hash['Transactions'].each do |structure|
          transactions << (Transaction.from_hash(structure) if structure)
        end
      end

      transactions = SKIP unless hash.key?('Transactions')

      # Create object from extracted values.
      GetTransactionsResponse.new(pagination_response,
                                  transactions)
    end
  end
end
