# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Get Prospect Stages Response Model
  class GetProspectStagesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # List of Prospect Stages
    # @return [Array[ProspectStage]]
    attr_accessor :prospect_stages

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['prospect_stages'] = 'ProspectStages'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        prospect_stages
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(prospect_stages = SKIP)
      @prospect_stages = prospect_stages unless prospect_stages == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      prospect_stages = nil
      unless hash['ProspectStages'].nil?
        prospect_stages = []
        hash['ProspectStages'].each do |structure|
          prospect_stages << (ProspectStage.from_hash(structure) if structure)
        end
      end

      prospect_stages = SKIP unless hash.key?('ProspectStages')

      # Create object from extracted values.
      GetProspectStagesResponse.new(prospect_stages)
    end
  end
end
