# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Get Payment Types Response Model
  class GetPaymentTypesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The requested payment types.
    # @return [Array[PaymentType]]
    attr_accessor :payment_types

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment_types'] = 'PaymentTypes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payment_types
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment_types = SKIP)
      @payment_types = payment_types unless payment_types == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      payment_types = nil
      unless hash['PaymentTypes'].nil?
        payment_types = []
        hash['PaymentTypes'].each do |structure|
          payment_types << (PaymentType.from_hash(structure) if structure)
        end
      end

      payment_types = SKIP unless hash.key?('PaymentTypes')

      # Create object from extracted values.
      GetPaymentTypesResponse.new(payment_types)
    end
  end
end
