# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetRequiredClientFieldsResponse Model.
  class GetRequiredClientFieldsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A list of strings that maps to the client fields that are required by the
    # site.
    # @return [Array[String]]
    attr_accessor :required_client_fields

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['required_client_fields'] = 'RequiredClientFields'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        required_client_fields
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(required_client_fields = SKIP)
      @required_client_fields = required_client_fields unless required_client_fields == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      required_client_fields =
        hash.key?('RequiredClientFields') ? hash['RequiredClientFields'] : SKIP

      # Create object from extracted values.
      GetRequiredClientFieldsResponse.new(required_client_fields)
    end
  end
end
