# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # GetMembershipsResponse Model.
  class GetMembershipsResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Details about the memberships.
    # @return [Array[Membership]]
    attr_accessor :memberships

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['memberships'] = 'Memberships'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        memberships
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(memberships = SKIP)
      @memberships = memberships unless memberships == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      memberships = nil
      unless hash['Memberships'].nil?
        memberships = []
        hash['Memberships'].each do |structure|
          memberships << (Membership.from_hash(structure) if structure)
        end
      end

      memberships = SKIP unless hash.key?('Memberships')

      # Create object from extracted values.
      GetMembershipsResponse.new(memberships)
    end
  end
end
