# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Contains information about the get reservation response
  class GetReservationResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Contains information about the reservation details.
    # @return [Array[Reservation]]
    attr_accessor :reservations

    # Contains information about the pagination used.
    # @return [Pagination]
    attr_accessor :pagination

    # Contains information about the response message detail.
    # @return [ResponseDetails]
    attr_accessor :response_details

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['reservations'] = 'Reservations'
      @_hash['pagination'] = 'Pagination'
      @_hash['response_details'] = 'ResponseDetails'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        reservations
        pagination
        response_details
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(reservations = SKIP, pagination = SKIP,
                   response_details = SKIP)
      @reservations = reservations unless reservations == SKIP
      @pagination = pagination unless pagination == SKIP
      @response_details = response_details unless response_details == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      reservations = nil
      unless hash['Reservations'].nil?
        reservations = []
        hash['Reservations'].each do |structure|
          reservations << (Reservation.from_hash(structure) if structure)
        end
      end

      reservations = SKIP unless hash.key?('Reservations')
      pagination = Pagination.from_hash(hash['Pagination']) if hash['Pagination']
      response_details = ResponseDetails.from_hash(hash['ResponseDetails']) if
        hash['ResponseDetails']

      # Create object from extracted values.
      GetReservationResponse.new(reservations,
                                 pagination,
                                 response_details)
    end
  end
end
