# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # PricingRelationships Model.
  class PricingRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Integer]]
    attr_accessor :pays_for

    # TODO: Write general description for this method
    # @return [Array[Integer]]
    attr_accessor :paid_by

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pays_for'] = 'PaysFor'
      @_hash['paid_by'] = 'PaidBy'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pays_for
        paid_by
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pays_for = SKIP, paid_by = SKIP)
      @pays_for = pays_for unless pays_for == SKIP
      @paid_by = paid_by unless paid_by == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pays_for = hash.key?('PaysFor') ? hash['PaysFor'] : SKIP
      paid_by = hash.key?('PaidBy') ? hash['PaidBy'] : SKIP

      # Create object from extracted values.
      PricingRelationships.new(pays_for,
                               paid_by)
    end
  end
end
