# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module MindbodyPublicApi
  # PromoCode Model.
  class PromoCode < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # ID of the promo code
    # @return [Integer]
    attr_accessor :promotion_id

    # Name of the promo code
    # @return [String]
    attr_accessor :name

    # The code of the promocode.
    # @return [String]
    attr_accessor :code

    # Indicates that promocode is active.
    # @return [TrueClass | FalseClass]
    attr_accessor :active

    # Discount for a promo code
    # @return [Discount]
    attr_accessor :discount

    # The promocode activation date.
    # @return [DateTime]
    attr_accessor :activation_date

    # The promocode expiration date.
    # @return [DateTime]
    attr_accessor :expiration_date

    # The maximun number of uses.
    # @return [Integer]
    attr_accessor :max_uses

    # Number of Autopays
    # @return [Integer]
    attr_accessor :number_of_autopays

    # The number of days a client has to use a promocode after they are no
    # longer a prospect.
    # @return [Integer]
    attr_accessor :days_after_close_date

    # Indicates if promocode to be redeemed online in consumer mode.
    # @return [TrueClass | FalseClass]
    attr_accessor :allow_online

    # Promo code last modified date and time
    # @return [DateTime]
    attr_accessor :last_modified_date_time

    # What days the promo code can be used
    # @return [Array[DaysValidEnum]]
    attr_accessor :days_valid

    # Contains information about a promocode applicable items.
    # @return [Array[ApplicableItem]]
    attr_accessor :applicable_items

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['promotion_id'] = 'PromotionID'
      @_hash['name'] = 'Name'
      @_hash['code'] = 'Code'
      @_hash['active'] = 'Active'
      @_hash['discount'] = 'Discount'
      @_hash['activation_date'] = 'ActivationDate'
      @_hash['expiration_date'] = 'ExpirationDate'
      @_hash['max_uses'] = 'MaxUses'
      @_hash['number_of_autopays'] = 'NumberOfAutopays'
      @_hash['days_after_close_date'] = 'DaysAfterCloseDate'
      @_hash['allow_online'] = 'AllowOnline'
      @_hash['last_modified_date_time'] = 'LastModifiedDateTime'
      @_hash['days_valid'] = 'DaysValid'
      @_hash['applicable_items'] = 'ApplicableItems'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        promotion_id
        name
        code
        active
        discount
        activation_date
        expiration_date
        max_uses
        number_of_autopays
        days_after_close_date
        allow_online
        last_modified_date_time
        days_valid
        applicable_items
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(promotion_id = SKIP, name = SKIP, code = SKIP, active = SKIP,
                   discount = SKIP, activation_date = SKIP,
                   expiration_date = SKIP, max_uses = SKIP,
                   number_of_autopays = SKIP, days_after_close_date = SKIP,
                   allow_online = SKIP, last_modified_date_time = SKIP,
                   days_valid = SKIP, applicable_items = SKIP)
      @promotion_id = promotion_id unless promotion_id == SKIP
      @name = name unless name == SKIP
      @code = code unless code == SKIP
      @active = active unless active == SKIP
      @discount = discount unless discount == SKIP
      @activation_date = activation_date unless activation_date == SKIP
      @expiration_date = expiration_date unless expiration_date == SKIP
      @max_uses = max_uses unless max_uses == SKIP
      @number_of_autopays = number_of_autopays unless number_of_autopays == SKIP
      @days_after_close_date = days_after_close_date unless days_after_close_date == SKIP
      @allow_online = allow_online unless allow_online == SKIP
      @last_modified_date_time = last_modified_date_time unless last_modified_date_time == SKIP
      @days_valid = days_valid unless days_valid == SKIP
      @applicable_items = applicable_items unless applicable_items == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      promotion_id = hash.key?('PromotionID') ? hash['PromotionID'] : SKIP
      name = hash.key?('Name') ? hash['Name'] : SKIP
      code = hash.key?('Code') ? hash['Code'] : SKIP
      active = hash.key?('Active') ? hash['Active'] : SKIP
      discount = Discount.from_hash(hash['Discount']) if hash['Discount']
      activation_date = if hash.key?('ActivationDate')
                          (DateTimeHelper.from_rfc3339(hash['ActivationDate']) if hash['ActivationDate'])
                        else
                          SKIP
                        end
      expiration_date = if hash.key?('ExpirationDate')
                          (DateTimeHelper.from_rfc3339(hash['ExpirationDate']) if hash['ExpirationDate'])
                        else
                          SKIP
                        end
      max_uses = hash.key?('MaxUses') ? hash['MaxUses'] : SKIP
      number_of_autopays =
        hash.key?('NumberOfAutopays') ? hash['NumberOfAutopays'] : SKIP
      days_after_close_date =
        hash.key?('DaysAfterCloseDate') ? hash['DaysAfterCloseDate'] : SKIP
      allow_online = hash.key?('AllowOnline') ? hash['AllowOnline'] : SKIP
      last_modified_date_time = if hash.key?('LastModifiedDateTime')
                                  (DateTimeHelper.from_rfc3339(hash['LastModifiedDateTime']) if hash['LastModifiedDateTime'])
                                else
                                  SKIP
                                end
      days_valid = hash.key?('DaysValid') ? hash['DaysValid'] : SKIP
      # Parameter is an array, so we need to iterate through it
      applicable_items = nil
      unless hash['ApplicableItems'].nil?
        applicable_items = []
        hash['ApplicableItems'].each do |structure|
          applicable_items << (ApplicableItem.from_hash(structure) if structure)
        end
      end

      applicable_items = SKIP unless hash.key?('ApplicableItems')

      # Create object from extracted values.
      PromoCode.new(promotion_id,
                    name,
                    code,
                    active,
                    discount,
                    activation_date,
                    expiration_date,
                    max_uses,
                    number_of_autopays,
                    days_after_close_date,
                    allow_online,
                    last_modified_date_time,
                    days_valid,
                    applicable_items)
    end

    def to_custom_activation_date
      DateTimeHelper.to_rfc3339(activation_date)
    end

    def to_custom_expiration_date
      DateTimeHelper.to_rfc3339(expiration_date)
    end

    def to_custom_last_modified_date_time
      DateTimeHelper.to_rfc3339(last_modified_date_time)
    end
  end
end
