# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Choice that decides whether the availablity should be publicly visible,
  # masked or hidden.
  class PublicDisplayEnum
    PUBLIC_DISPLAY_ENUM = [
      # TODO: Write general description for HIDE
      HIDE = 'Hide'.freeze,

      # TODO: Write general description for SHOW
      SHOW = 'Show'.freeze,

      # TODO: Write general description for MASK
      MASK = 'Mask'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PUBLIC_DISPLAY_ENUM.include?(value)
    end
  end
end
