# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # Request to send a password reset email to a user
  class SendPasswordResetEmailRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The user’s email address. The software uses this parameter as the
    # username.
    # @return [String]
    attr_accessor :user_email

    # The user’s first name. The software uses this parameter to verify the
    # user.
    # @return [String]
    attr_accessor :user_first_name

    # The user’s last name. The software uses this parameter to verify the user.
    # @return [String]
    attr_accessor :user_last_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['user_email'] = 'UserEmail'
      @_hash['user_first_name'] = 'UserFirstName'
      @_hash['user_last_name'] = 'UserLastName'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(user_email = nil, user_first_name = nil,
                   user_last_name = nil)
      @user_email = user_email
      @user_first_name = user_first_name
      @user_last_name = user_last_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      user_email = hash.key?('UserEmail') ? hash['UserEmail'] : nil
      user_first_name = hash.key?('UserFirstName') ? hash['UserFirstName'] : nil
      user_last_name = hash.key?('UserLastName') ? hash['UserLastName'] : nil

      # Create object from extracted values.
      SendPasswordResetEmailRequest.new(user_email,
                                        user_first_name,
                                        user_last_name)
    end
  end
end
