# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # StoredCardInfo Model.
  class StoredCardInfo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :last_four

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['last_four'] = 'LastFour'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        last_four
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(last_four = SKIP)
      @last_four = last_four unless last_four == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      last_four = hash.key?('LastFour') ? hash['LastFour'] : SKIP

      # Create object from extracted values.
      StoredCardInfo.new(last_four)
    end
  end
end
