# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # UpdateClientServiceResponse Model.
  class UpdateClientServiceResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A service that is on a client's account.
    # @return [ClientService]
    attr_accessor :client_service

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client_service'] = 'ClientService'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        client_service
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(client_service = SKIP)
      @client_service = client_service unless client_service == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      client_service = ClientService.from_hash(hash['ClientService']) if hash['ClientService']

      # Create object from extracted values.
      UpdateClientServiceResponse.new(client_service)
    end
  end
end
