# mindbody_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MindbodyPublicApi
  # UpdateClientResponse Model.
  class UpdateClientResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A Client DTO with Suspension Informatoin
    # @return [ClientWithSuspensionInfo]
    attr_accessor :client

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client'] = 'Client'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        client
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(client = SKIP)
      @client = client unless client == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      client = ClientWithSuspensionInfo.from_hash(hash['Client']) if hash['Client']

      # Create object from extracted values.
      UpdateClientResponse.new(client)
    end
  end
end
